# 2021 KUS Honors Final Project
## Team 1 ESG

Se Eun Kim, Su Hyung Choi, Sin Ho Yoo, Jae Ho Ahn, Seung Jun Lee

Advisor Prof. Dong Haun Lee

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df_2021 = pd.read_excel('2021.xlsx')
df_2020 = pd.read_excel('2020.xlsx')
df_esg2021 = pd.read_excel('esg_2021.xlsx')
df_esg2020 = pd.read_excel('esg_2020.xlsx')

## **Data Preprocessing**

Drop the columns of ESG csv

In [ ]:
df_esg2020 = df_esg2020.drop(df_esg2020.columns[8:], axis=1)
df_esg2020 = df_esg2020.drop(df_esg2020.columns[[0, 1]], axis = 1)
df_esg2020.head()

df_esg2021 = df_esg2021.drop(df_esg2021.columns[8:], axis=1)
df_esg2021 = df_esg2021.drop(df_esg2021.columns[[0, 1]], axis = 1)
df_esg2021.head()

      종목명    종목코드 종합등급 환경  사회 지배구조
0  AJ네트웍스   95570    B  D   B    B
1   AK홀딩스    6840   B+  B  B+   B+
2   AP시스템  265520    D  D   D    C
3     BGF   27410    A  A  A+    A
4  BGF리테일  282330    A  A  A+    A

Drop rows of nan value of df_2020, df_2021

In [ ]:
df_2021.dropna(inplace=True)
df_2020.dropna(inplace=True)

In [ ]:
# create columns of df_2020, df_2021 of Final Grade, Environment, Social, Governance

df_2021['Final Grade'] = range(0, df_2021.shape[0])
df_2021['Environment'] = range(0, df_2021.shape[0])
df_2021['Social'] = range(0, df_2021.shape[0])
df_2021['Governance'] = range(0, df_2021.shape[0])

df_2020['Final Grade'] = range(0, df_2020.shape[0])
df_2020['Environment'] = range(0, df_2020.shape[0])
df_2020['Social'] = range(0, df_2020.shape[0])
df_2020['Governance'] = range(0, df_2020.shape[0])

In [ ]:
for index, item in enumerate(df_2020['Name']):
  for data_index, data_item in enumerate(df_esg2020['종목명']):
    if item == data_item:
      df_2020.iloc[index, df_2021.columns.get_loc('Final Grade')] = df_esg2020.iloc[data_index, df_esg2020.columns.get_loc('종합등급')]
      df_2020.iloc[index, df_2021.columns.get_loc('Environment')] = df_esg2020.iloc[data_index, df_esg2020.columns.get_loc('환경')]
      df_2020.iloc[index, df_2021.columns.get_loc('Social')] = df_esg2020.iloc[data_index, df_esg2020.columns.get_loc('사회')]
      df_2020.iloc[index, df_2021.columns.get_loc('Governance')] = df_esg2020.iloc[data_index, df_esg2020.columns.get_loc('지배구조')]


for index, item in enumerate(df_2021['Name']):
  for data_index, data_item in enumerate(df_esg2020['종목명']):
    if item == data_item:
      df_2021.iloc[index, df_2021.columns.get_loc('Final Grade')] = df_esg2021.iloc[data_index, df_esg2021.columns.get_loc('종합등급')]
      df_2021.iloc[index, df_2021.columns.get_loc('Environment')] = df_esg2021.iloc[data_index, df_esg2021.columns.get_loc('환경')]
      df_2021.iloc[index, df_2021.columns.get_loc('Social')] = df_esg2021.iloc[data_index, df_esg2021.columns.get_loc('사회')]
      df_2021.iloc[index, df_2021.columns.get_loc('Governance')] = df_esg2021.iloc[data_index, df_esg2021.columns.get_loc('지배구조')]

In [ ]:
str_exp = "Environment in ['A+', 'A', 'B+', 'B', 'C', 'D']"
df_2021_esg = df_2021.query(str_exp)

str_exp = "Environment in ['A+', 'A', 'B+', 'B', 'C', 'D']"
df_2020_esg = df_2020.query(str_exp)

str_exp = "Environment not in ['A+', 'A', 'B+', 'B', 'C', 'D']"
df_2021_no_esg = df_2021.query(str_exp)

str_exp = "Environment not in ['A+', 'A', 'B+', 'B', 'C', 'D']"
df_2020_no_esg = df_2020.query(str_exp)

In [ ]:
df_2021_esg.head()

      Stock    Name   전화번호/0A1090  ... Environment  Social  Governance
4   36460.0  한국가스공사  053-670-0114  ...           C       B          B+
5   33780.0   케이티앤지  080-931-0399  ...           D       C           C
7   67080.0    대화제약   02-586-6451  ...           B       B           B
25  23810.0      인팩  02-3432-3333  ...          B+       A          B+
35  29960.0     코엔텍  052-228-7300  ...           C       C          B+

[5 rows x 27 columns]

In [ ]:
df_2021_esg.drop(df_2021_esg.columns[[6, 7, 8, 12, 16, 17]], axis = 1, inplace = True)#6, 7, 8, 12, 15, 16, 17, 20, 21
df_2020_esg.drop(df_2020_esg.columns[[6, 7, 8, 12, 16, 17]], axis = 1, inplace = True)
df_2021_no_esg.drop(df_2021_no_esg.columns[[6, 7, 8, 12, 16, 17]], axis = 1, inplace = True)
df_2020_no_esg.drop(df_2020_no_esg.columns[[6, 7, 8, 12, 16, 17]], axis = 1, inplace = True)

# df_2021_esg.iloc[:, 4: 17] = df_2021_esg.iloc[: , 4: 17].apply(lambda x: np.log(x))
# df_2020_esg.iloc[:, 4: 17] = df_2020_esg.iloc[:, 4: 17].apply(lambda x: np.log(x))

df_2021_esg.dropna(inplace=True)
df_2020_esg.dropna(inplace=True)

df_2020_esg.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

      Stock    Name   전화번호/0A1090  ... Environment  Social  Governance
3   84110.0  휴온스글로벌   02-854-4700  ...           D      B+           B
5   33780.0   케이티앤지  080-931-0399  ...          B+      B+           A
25  23810.0      인팩  02-3432-3333  ...           C       C           B
30  56700.0   신화인터텍  041-590-3300  ...           B       B           B
35  29960.0     코엔텍  052-228-7300  ...           B       B           B

[5 rows x 21 columns]

In [ ]:
def discretization(df, regression = False):
  _df = df.copy()
  if regression is False:
    for col in ['Final Grade', 'Environment', 'Social', 'Governance']:
      for index, item in enumerate(_df[col]):
        if item == 'A+':
          _df.iloc[index, _df.columns.get_loc(col)] = 1#1
        elif item == 'A':
          _df.iloc[index, _df.columns.get_loc(col)] = 1#0.9
        elif item == 'B+':
          _df.iloc[index, _df.columns.get_loc(col)] = 2#0.8
        elif item == 'B':
          _df.iloc[index, _df.columns.get_loc(col)] = 2#0.7
        elif item == 'C':
          _df.iloc[index, _df.columns.get_loc(col)] = 3#0.5
        elif item == 'D':
          _df.iloc[index, _df.columns.get_loc(col)] = 4#0.3
    return _df
  else:
    for col in ['Final Grade', 'Environment', 'Social', 'Governance']:
      for index, item in enumerate(_df[col]):
        if item == 'A+':
          _df.iloc[index, _df.columns.get_loc(col)] = 1
        elif item == 'A':
          _df.iloc[index, _df.columns.get_loc(col)] = 0.9
        elif item == 'B+':
          _df.iloc[index, _df.columns.get_loc(col)] = 0.8
        elif item == 'B':
          _df.iloc[index, _df.columns.get_loc(col)] = 0.7
        elif item == 'C':
          _df.iloc[index, _df.columns.get_loc(col)] = 0.6
        elif item == 'D':
          _df.iloc[index, _df.columns.get_loc(col)] = 0.5
    return _df

_df_2021_esg = df_2021_esg
_df_2020_esg = df_2020_esg

df_2021_esg = discretization(_df_2021_esg)
df_2020_esg = discretization(_df_2020_esg)

df_2021_esg_reg = discretization(_df_2021_esg, True)
df_2020_esg_reg = discretization(_df_2020_esg, True)

df_2021_esg.columns = ['Stock No.', 'Name', 'Phone', 'Class', 'PER', 'PBR', 'Debt Ratio', 'Volatility Ratio', 'Net return on equity capital', 'Inventory asset turnover', 'EV', 'Accounts receivables turnover', 'PCR', 'net sales growth rate', 'Profit Margin', '주가/순유동자산',	'영업이익률', 'Final Grade', 'Envrionment', 'Social', 'Governance']
df_2020_esg.columns = ['Stock No.', 'Name', 'Phone', 'Class', 'PER', 'PBR', 'Debt Ratio', 'Volatility Ratio', 'Net return on equity capital', 'Inventory asset turnover', 'EV', 'Accounts receivables turnover', 'PCR', 'net sales growth rate', 'Profit Margin', '주가/순유동자산',	'영업이익률', 'Final Grade', 'Envrionment', 'Social', 'Governance']

df_2021_esg_reg.columns = ['Stock No.', 'Name', 'Phone', 'Class', 'PER', 'PBR', 'Debt Ratio', 'Volatility Ratio', 'Net return on equity capital', 'Inventory asset turnover', 'EV', 'Accounts receivables turnover', 'PCR', 'net sales growth rate', 'Profit Margin', '주가/순유동자산',	'영업이익률', 'Final Grade', 'Envrionment', 'Social', 'Governance']
df_2020_esg_reg.columns = ['Stock No.', 'Name', 'Phone', 'Class', 'PER', 'PBR', 'Debt Ratio', 'Volatility Ratio', 'Net return on equity capital', 'Inventory asset turnover', 'EV', 'Accounts receivables turnover', 'PCR', 'net sales growth rate', 'Profit Margin', '주가/순유동자산',	'영업이익률', 'Final Grade', 'Envrionment', 'Social', 'Governance']

# df_2021_esg.columns = ['Stock No.', 'Name', 'Phone', 'Class', 'PER', 'PBR', 'Debt Ratio', 'Volatility Ratio', 'Net return on equity capital', 'Inventory asset turnover', 'Accounts receivables turnover', 'PCR', 'net sales growth rate', 'Profit Margin', 'Final Grade', 'Envrionment', 'Social', 'Governance']
# df_2020_esg.columns = ['Stock No.', 'Name', 'Phone', 'Class', 'PER', 'PBR', 'Debt Ratio', 'Volatility Ratio', 'Net return on equity capital', 'Inventory asset turnover', 'Accounts receivables turnover', 'PCR', 'net sales growth rate', 'Profit Margin', 'Final Grade', 'Envrionment', 'Social', 'Governance']

df_2021_esg_reg.head()

    Stock No.    Name         Phone  ... Envrionment  Social  Governance
4     36460.0  한국가스공사  053-670-0114  ...         0.6     0.7         0.8
5     33780.0   케이티앤지  080-931-0399  ...         0.5     0.6         0.6
7     67080.0    대화제약   02-586-6451  ...         0.7     0.7         0.7
25    23810.0      인팩  02-3432-3333  ...         0.8     0.9         0.8
35    29960.0     코엔텍  052-228-7300  ...         0.6     0.6         0.8

[5 rows x 21 columns]

### Download Files

In [ ]:
# from google.colab import files
# df_2021_esg.to_csv('df_2021_esg.csv')
# files.download('df_2021_esg.csv')

# from google.colab import files
# df_2021_no_esg.to_csv('df_2021_no_esg.csv')
# files.download('df_2021_no_esg.csv')

# from google.colab import files
# df_2020_esg.to_csv('df_2020_esg.csv')
# files.download('df_2020_esg.csv')

# from google.colab import files
# df_2020_no_esg.to_csv('df_2020_no_esg.csv')
# files.download('df_2020_no_esg.csv')

## **Split the Data for train, test**

### Dataset for classification

In [ ]:
from sklearn.model_selection import train_test_split

#for financial features
x_train_2021, x_test_2021, y_train_2021, y_test_2021 = train_test_split(df_2021_esg.iloc[:, 4 : 17], df_2021_esg.iloc[:, 17], test_size=0.33, random_state=55)
x_train_2020, x_test_2020, y_train_2020, y_test_2020 = train_test_split(df_2020_esg.iloc[:, 4 : 17], df_2020_esg.iloc[:, 17], test_size=0.33, random_state=55)

x_train = pd.concat([x_train_2021, x_train_2020]).values
x_test = pd.concat([x_test_2021, x_test_2020]).values

y_train = pd.concat([y_train_2021, y_train_2020]).astype('int').values
y_test = pd.concat([y_test_2021, y_test_2020]).astype('int').values

#for esg features only
x_train_2021_esg, x_test_2021_esg, y_train_2021_esg, y_test_2021_esg = train_test_split(df_2021_esg.iloc[:, 18 : ], df_2021_esg.iloc[:, 17], test_size=0.33, random_state=55)
x_train_2020_esg, x_test_2020_esg, y_train_2020_esg, y_test_2020_esg = train_test_split(df_2020_esg.iloc[:, 18 : ], df_2020_esg.iloc[:, 17], test_size=0.33, random_state=55)

x_train_esg = pd.concat([x_train_2021_esg, x_train_2020_esg]).values
x_test_esg = pd.concat([x_test_2021_esg, x_test_2020_esg]).values

y_train_esg = pd.concat([y_train_2021_esg, y_train_2020_esg]).astype('int').values
y_test_esg = pd.concat([y_test_2021_esg, y_test_2020_esg]).astype('int').values

### Dataset for regression

In [ ]:
from sklearn.model_selection import train_test_split

#for financial features
x_train_2021_reg, x_test_2021_reg, y_train_2021_reg, y_test_2021_reg = train_test_split(df_2021_esg_reg.iloc[:, 4 : 17], df_2021_esg_reg.iloc[:, 17], test_size=0.33, random_state=55)
x_train_2020_reg, x_test_2020_reg, y_train_2020_reg, y_test_2020_reg = train_test_split(df_2020_esg_reg.iloc[:, 4 : 17], df_2020_esg_reg.iloc[:, 17], test_size=0.33, random_state=55)

x_train_reg = pd.concat([x_train_2021_reg, x_train_2020_reg]).values
x_test_reg = pd.concat([x_test_2021_reg, x_test_2020_reg]).values

y_train_reg = pd.concat([y_train_2021_reg, y_train_2020_reg]).astype('float').values
y_test_reg = pd.concat([y_test_2021_reg, y_test_2020_reg]).astype('float').values

#for esg features only
x_train_2021_esg_reg, x_test_2021_esg_reg, y_train_2021_esg_reg, y_test_2021_esg_reg = train_test_split(df_2021_esg_reg.iloc[:, 18 : ], df_2021_esg_reg.iloc[:, 17], test_size=0.33, random_state=55)
x_train_2020_esg_reg, x_test_2020_esg_reg, y_train_2020_esg_reg, y_test_2020_esg_reg = train_test_split(df_2020_esg_reg.iloc[:, 18 : ], df_2020_esg_reg.iloc[:, 17], test_size=0.33, random_state=55)

x_train_esg_reg = pd.concat([x_train_2021_esg_reg, x_train_2020_esg_reg]).values
x_test_esg_reg = pd.concat([x_test_2021_esg_reg, x_test_2020_esg_reg]).values

y_train_esg_reg = pd.concat([y_train_2021_esg_reg, y_train_2020_esg_reg]).astype('float').values
y_test_esg_reg = pd.concat([y_test_2021_esg_reg, y_test_2020_esg_reg]).astype('float').values

In [ ]:
def regression_acc(x, y, net):

  sum = 0
  correct = 0

  x = np.array(x, dtype=float)
  y = np.array(y, dtype=float)

  y = y.reshape(-1, 1)

  for index, _y in enumerate(y):
    pred = net.predict([x[index]])
    sum = sum + 1
    if _y == round(pred[0], 1):
      correct = correct + 1

  return correct / sum



def classifier(sample_x, sample_y, x, y, net, name):

  print(name, '\n')

  sample_x = np.array(sample_x, dtype=float)
  sample_y = np.array(sample_y, dtype=float)

  print('Sample predicted: ', np.array(net.predict([sample_x])[0]))
  print('Sample Label: ', sample_y)

  acc = net.score(x, y)
  print('accuracy: ', acc)

  print()



def predictor(sample_x, sample_y, x, y, net, name):

  print(name, '\n')

  pred = net.predict([sample_x])

  print('Sample Label: ', np.array(sample_y))
  print('Sample Predicted: ', pred[0])

  acc = regression_acc(x, y, net)

  print('accuracy: ', acc)

  print()

## **Train with only ESG Features**

### Classficiation with Classsfier

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier

logistic = LogisticRegression(random_state=0, max_iter = 1000).fit(x_train_esg, y_train_esg)
sgd = SGDClassifier(loss="squared_hinge", alpha=0.03, penalty="l2", max_iter=10000).fit(x_train_esg, y_train_esg)

logistic.fit(x_train_esg, y_train_esg)
sgd.fit(x_train_esg, y_train_esg)

#sample data

sample_x = x_test_esg[1]
sample_y = y_test_esg[1]

#Logistic Regression

classifier(sample_x, sample_y, x_test_esg, y_test_esg, logistic, "Logistic Classifier")

#Stochastic Gradient Descent

classifier(sample_x, sample_y, x_test_esg, y_test_esg, sgd, "SGD Classifier")

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:700: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,

Logistic Classifier

Sample predicted:  2
Sample Label:  2.0
accuracy:  0.8396624472573839

SGD Classifier

Sample predicted:  2
Sample Label:  2.0
accuracy:  0.7763713080168776

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:700: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,

### Classification using Regression

In [ ]:
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Ridge
from sklearn import svm
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

elastic = ElasticNet(random_state=0)
#elastic = make_pipeline(StandardScaler(), ElasticNet(random_state=0))
elastic.fit(x_train_esg_reg, y_train_esg_reg)

logistic = LogisticRegression(random_state=0, max_iter = 1000)
# logistic = make_pipeline(StandardScaler(), LogisticRegression(random_state=0, max_iter = 1000))
# logistic.fit(x_train_esg_reg, y_train_esg_reg)

ridge = Ridge(random_state=0, alpha=.5, max_iter= 30000)
#ridge = make_pipeline(StandardScaler(), Ridge(random_state=0, alpha=.5, max_iter= 30000))
ridge.fit(x_train_esg_reg, y_train_esg_reg)

svr = svm.NuSVR()
#svr = make_pipeline(StandardScaler(), svm.NuSVR())
svr.fit(x_train_esg_reg, y_train_esg_reg)

sgd = SGDRegressor(max_iter=1000, tol=1e-3)
#sgd = make_pipeline(StandardScaler(), SGDRegressor(max_iter=1000, tol=1e-3))
sgd.fit(x_train_esg_reg, y_train_esg_reg)

#sample data
sample_x = x_test_esg_reg[1]
sample_y = y_test_esg_reg[1]

predictor(sample_x, sample_y, x_test_esg_reg, y_test_esg_reg, elastic, "Elastic Net")
# predictor(sample_x, sample_y, x_test_esg_reg, y_test_esg_reg, logistic, "Logistic Regression")
predictor(sample_x, sample_y, x_test_esg_reg, y_test_esg_reg, ridge, "Ridge Regression")
#predictor(sample_x, sample_y, x_test_esg_reg, y_test_esg_reg, svr, "SV Regression")
predictor(sample_x, sample_y, x_test_esg_reg, y_test_esg_reg, sgd, "SGD Regression")

Elastic Net

Sample Label:  0.7
Sample Predicted:  0.7163522012578616
accuracy:  0.31223628691983124

Ridge Regression

Sample Label:  0.7
Sample Predicted:  0.677920443054994
accuracy:  0.7890295358649789

SGD Regression

Sample Label:  0.7
Sample Predicted:  0.6906555433158512
accuracy:  0.6751054852320675

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:561: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:561: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:561: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)



```
# 코드로 형식 지정됨
```

## **Train with financial features**

### Classification using Classifier

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier


from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

logistic = LogisticRegression(random_state=0)
sgd = SGDClassifier(loss="hinge", penalty="l1", max_iter=3000)
svm = svm.SVC(kernel="rbf", degree=10, probability=True)
mlp = MLPClassifier(solver='adam', alpha=1e-4, hidden_layer_sizes=(20, 20, 6), max_iter=25, random_state=1)
rf = RandomForestClassifier(max_depth=100, random_state=0)
ada = AdaBoostClassifier(n_estimators=100)

#logistic = make_pipeline(StandardScaler(), logistic)
logistic.fit(x_train, y_train)

#sgd = make_pipeline(StandardScaler(), sgd)
sgd.fit(x_train, y_train)

#svm = make_pipeline(StandardScaler(), svm)
svm.fit(x_train, y_train)

#mlp = make_pipeline(StandardScaler(), mlp)
mlp.fit(x_train, y_train)

#rf = make_pipeline(StandardScaler(), rf)
rf.fit(x_train, y_train)

#ada = make_pipeline(StandardScaler(), ada)
ada.fit(x_train, y_train)

#sample data
sample_x = x_test[1]
sample_y = y_test[1]

classifier(sample_x, sample_y, x_test, y_test, sgd, "SGD")
classifier(sample_x, sample_y, x_test, y_test, logistic, "Logistic Regression")
classifier(sample_x, sample_y, x_test, y_test, mlp, "MLP")
classifier(sample_x, sample_y, x_test, y_test, rf, "Random Forest")
classifier(sample_x, sample_y, x_test, y_test, ada, "ADA Boost")

SGD

Sample predicted:  1
Sample Label:  2.0
accuracy:  0.15611814345991562

Logistic Regression

Sample predicted:  1
Sample Label:  2.0
accuracy:  0.2320675105485232

MLP

Sample predicted:  2
Sample Label:  2.0
accuracy:  0.39662447257383965

Random Forest

Sample predicted:  3
Sample Label:  2.0
accuracy:  0.5021097046413502

ADA Boost

Sample predicted:  1
Sample Label:  2.0
accuracy:  0.48945147679324896

### Classification using Regression

In [ ]:
from sklearn.linear_model import ElasticNet
#from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Ridge
from sklearn import svm
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

elastic = make_pipeline(StandardScaler(), ElasticNet(random_state=0))
elastic.fit(x_train_reg, y_train_reg)

# logistic = make_pipeline(StandardScaler(), LogisticRegression(random_state=0, max_iter = 1000))
# logistic.fit(x_train_reg, y_train_reg)

ridge = make_pipeline(StandardScaler(), Ridge(random_state=0, alpha=.5, max_iter= 30000))
ridge.fit(x_train_reg, y_train_reg)

svr = make_pipeline(StandardScaler(), svm.NuSVR())
svr.fit(x_train_reg, y_train_reg)

sgd = SGDRegressor(max_iter=5000, alpha=0.003, tol=1e-3)
#sgd = make_pipeline(StandardScaler(), SGDRegressor(max_iter=5000, alpha=0.003, tol=1e-3))
sgd.fit(x_train_reg, y_train_reg)
print(sgd.coef_)

#sample data
sample_x = x_test_reg[1]
sample_y = y_test_reg[1]

predictor(sample_x, sample_y, x_test_reg, y_test_reg, elastic, "Elastic Net")
predictor(sample_x, sample_y, x_test_reg, y_test_reg, logistic, "Logistic Regression")
predictor(sample_x, sample_y, x_test_reg, y_test_reg, ridge, "Ridge Regression")
predictor(sample_x, sample_y, x_test_reg, y_test_reg, svr, "SV Regression")
predictor(sample_x, sample_y, x_test_reg, y_test_reg, sgd, "SGD Regression")

[ 3.41467581e+12  1.54286482e+11 -1.73805638e+13  4.36620213e+13
  4.23533422e+10  3.58742007e+13  7.70350495e+11  2.92463803e+20
 -3.23200812e+13  3.09961793e+12 -2.51610126e+20 -1.90782373e+06
  2.75013005e+12]
Elastic Net

Sample Label:  0.7
Sample Predicted:  0.7163522012578616
accuracy:  0.31223628691983124

Logistic Regression

Sample Label:  0.7
Sample Predicted:  1
accuracy:  0.012658227848101266

Ridge Regression

Sample Label:  0.7
Sample Predicted:  0.700519507001754
accuracy:  0.29957805907172996

SV Regression

Sample Label:  0.7
Sample Predicted:  0.6595682283676894
accuracy:  0.31645569620253167

SGD Regression

Sample Label:  0.7
Sample Predicted:  4.006996131622845e+29
accuracy:  0.0